agents/mcp.mdx
The "optional authorization mechanisms" link was broken on the MCP page (was pointing to a draft URL that's been removed now). This PR updates to use the current spec URL.
* Updated the URL in the MCP authentication warning from an outdated draft link to the current specification link, ensuring accurate documentation regarding authorization mechanisms for enhanced clarity and correctness.
=> fix: Fixes broken MCP external link (was pointing to the draft)

agents/langchain.mdx, agents/mcp.mdx
Adds information on which API scopes are required for both the MCP and Langchain integrations. 
* Added sections detailing API tokens required for Glean integration, highlighting the need for user-scoped tokens with specific scopes: `chat` and `search`. Sections for configuring environment variables were also expanded.
=> docs: Adds information on which scopes to use for API tokens for MCP/Langchain

agents/mcp.mdx
#23 added documentation to run the `configure` command to aid in configuring the MCP server. The docs added to this repo unintentionally omitted that subcommand. This PR addresses that.
* Updated `npx @gleanwork/mcp-server` commands by adding the `configure` subcommand to improve clarity and functionality in command usage, replacing direct calls with enhanced structure for configuration processes.
=> fix: Fixes npx command to include the configure subcommand

_overrides/alpha_endpoints/alpha-endpoints.js
Looks like this
Of course, these paths are internal right now so this causes no changes to the site
Stolen from John's deprecation stuff.
=> [NI] Add alpha endpoint support for UI

_overrides/alpha_endpoints/alpha-endpoints.js, _overrides/deprecations/deprecated.js
Fixes issue where repeated clicks on the sidebar links for pages containing the alpha or deprecated warnings cause the div to be rendered multiple times.
=> fix: Fixes alpha and deprecated warnings duplications

client.mdx, indexing.mdx, indexing/people-teams-identity.mdx
Lots of our prs complain about broken links to `/api-reference/`.  As far as I can tell, the link checking happens with no regard for the generation configured in docs.json.
Updating the paths to full URLs is consistent with similar links, like the ones in changelog.mdx.
Note though, that the link checker doesn't actually *check* these links. It seems to skip links specified as full URLs.
=> chore: silence broken-links linting

actions/openapi.mdx, client/openapi.mdx, docs.json, indexing/authentication/managing-tokens.mdx, indexing/documents/document-model.mdx, indexing/openapi.mdx, sdk.mdx
We've created a new public repository, `gleanwork/open-api`, which houses our pre-processed specs. That repository should be considered the SOT for both our API client generation, and our documentation.
This change represents the first step in updating our docs with the API client references. Once those libraries are released, we'll point the specs to the enhanced versions, which will include our API client documentation.
* The pull request updates the `docs.json` file to change the sources for the "Indexing API" and "Client API" sections from `api.redocly.com` to the new public repository `gleanwork/open-api`. Specifically, it moves from URLs referencing `redocly` to referencing raw paths in `gleanwork/open-api`, thus aligning future API client generation and documentation under a single …
=> internal: Updates reference to client and indexing specs to point to gleanwork/open-api instead of redocly

docs.json
Even in light mode the codeblocks on the API pages were rendering in dark mode. This change ensures they render with the associated mode that's active.
* Added a new "styling" section to `docs.json`, including a setting for "codeblocks" to support rendering based on light/dark modes.
=> task: Ensure codeblocks render color based on light/dark modes

actions/examples/google-calendar-events.mdx, actions/examples/google-docs-update.mdx, actions/examples/jira-issue-creation.mdx, client/guides/chatbot.mdx
Redeployment of docs follow rename of `domain` to `instance` in API Clients. This more closely matches what this property represents.
We'll be following this change with a number of others in order to standardize the definition across our libraries etc.
* Updated API references from "domain" to "instance" in various files, clarifying that the instance name typically corresponds to the email domain without the extension. This change enhances clarity in the OAuth client configuration across different implementations.
* No linked documents to summarize.
=> docs: Updates references to domain after API Client rename from domain to instance

actions/examples/google-calendar-events.mdx, actions/examples/google-docs-update.mdx, actions/examples/jira-issue-creation.mdx
Domains have TLDs, not extensions.
Fast follow to #36.
=> docs: More precise terminology

indexing.mdx
- Add instance parameter to Glean client initialization
- Update document schema in examples:
- Add datasource field
- Replace url with viewURL
- Convert content to structured body object
- Update permissions format to use allowedUsers/allowedGroups
=> docs(indexing): update typescript documentation examples

_overrides/alpha_endpoints/beta-endpoints.js, docs.json
This pull request updates the handling of API endpoint warnings and enhances the documentation structure. The most significant changes involve renaming and updating the script for endpoint warnings and adding OpenAPI specifications to the documentation.
* Renamed `_overrides/alpha_endpoints/alpha-endpoints.js` to `_overrides/alpha_endpoints/beta-endpoints.js` and updated the script to reflect the transition from "alpha" to "beta" endpoints. This includes changing warning text, endpoint paths, and function names (`addAlphaWarning` to `addBetaWarning`).
* Updated the `innerHTML` of the warning callout to use the `betaWarningText` variable and adjusted the event listener to call `addBetaWarning` instead of `addAlphaWarning`.
* Updated `docs.json` to include OpenAPI specifications for the …
=> chore: Marks Agent APIs as Beta

changelog.mdx
- Documents required request body changes for search and recommendations endpoints
- Notes breaking change in Python client v0.5.0
=> docs(changelog): add entry for OpenAPI spec request body requirements

docs.json
This updates the various references for the OpenAPI specs to use a new stable path for the "final" spec location. This allows us to continue iterating the processing steps in gleanwork/open-api without breaking the site deployment.
~Requires https://github.com/gleanwork/open-api/pull/38 to land (and deploy to gh-pages) first.~
=> refactor: Use stable directory for OpenAPI Specs

changelog.mdx
Requires https://github.com/gleanwork/open-api/pull/42 to land and be deployed first.
Stacked on top of #62 (which needs to land first).
=> chore: Add changelog entry for API reference code snippet updates

api-clients.mdx
This was fixed for the `https://develpers.glean.com/client/api/` and `https://developers.glean.com/indexing/api/` a few days ago, but these examples are not driven from the generated code samples just yet (so they have to be manually updated).
=> fix: Add `instance` parameter to API client initialization

README.md, mise.toml
[mise](https://mise.jdx.dev/) is certainly not required but a bunch of us use it and this project configuration makes working in this project a little bit nicer (ensuring we all use the same versions of node, pnpm, and vale).
=> chore: Add mise.toml to make working in the repo easier

.github/workflows/format-on-merge.yml, .prettierignore, .prettierrc, package.json, pnpm-lock.yaml
Add `prettier` configuration to the repo. Folks using things like "format on save" today (prior to these changes) end up making quite a number of changes that are unrelated to their actual tweaks / modifications. Adding prettier here helps ensure that the repo stays in a consistent state.
Additionally, this adds a GitHub action to automatically fix code formatting on merge. This approach reduces friction for contributors by handling formatting automatically rather than requiring perfect adherence to style rules, which is especially beneficial for quick or drive-by contributions.
=> feat: Setup prettier to ensure consistent formatting

actions/examples/google-calendar-events.mdx, actions/examples/google-docs-update.mdx, changelog.mdx
In `.mdx` if you have the following:
```mdx
<div>
<Card>
- Some item here
</Card>
</div>
```
^ is a parse error:
```
17:3-17:10: Expected the closing tag `</Card>` either after the end of `listItem` (17:10) or another opening tag after the start of `listItem` (16:1)
```
This PR adds a comment in all of the locations where we have that issue, so that there is at least one linebreak between the end of the list item and the close of the component.
=> fix: Fix MDX parsing errors (close component after unindented list item)

client/chat.mdx
We call it out as:
```https://<your-domain>-be.glean.com/rest/api/v1/chat```
But then we state to replace it as `<your-domain-be>` (it should reference `<your-domain>`).
Fixes https://github.com/gleanwork/glean-developer-site/issues/50
=> fix: Incorrect reference to instance placeholder

.github/workflows/trigger-redeploy.yml, _redeploy-trigger.mdx
Add GitHub workflow to manually trigger redeployments. Includes workflow dispatch trigger and automatic commit of timestamp updates to `_redeploy-trigger.mdx` file. The `_redeploy-trigger.mdx` file is explictly excluded from search indexing and whatnot (see [Hidden Pages](https://mintlify.com/docs/guides/hidden-pages#search-and-seo)).
=> feat(ci): Add GitHub Actions workflow to trigger a redeployment

changelog.mdx
Looks like some MDX rendering changes broke how these entries were rendered. I've updated the formatting of the `.mdx` to be more idiomatic fixed the rendering issues.
=> fix: Rendering issues with changelog entries

_overrides/beta_endpoints/beta-endpoints.js
This pull request updates the file `_overrides/beta_endpoints/beta-endpoints.js` (renamed from `_overrides/alpha_endpoints/beta-endpoints.js`) to reflect changes in API endpoint paths and improve clarity in naming conventions.
* Updated the paths in the `betaPaths` array to use clearer and more descriptive naming conventions for the endpoints:
- Example: `/api-reference/client/agents/get-agent` is now `/client/api/agents/retrieve-an-agent`.
* Renamed the file from `_overrides/alpha_endpoints/beta-endpoints.js` to `_overrides/beta_endpoints/beta-endpoints.js` to align with the current naming convention.
=> fix: Adds beta labels back to Agent API pages (they were broken with the agent docs renames)
